#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("co.yat.android.container.Resource", IsApplication=true)]

namespace co.yat.android.container
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Novell.MonoDroid.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f040000
			public const int View_Title_Size = 2130968576;
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_launcher = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080000
			public const int button1 = 2131230720;
			
			// aapt resource value: 0x7f080002
			public const int button2 = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int menu_settings = 2131230723;
			
			// aapt resource value: 0x7f080001
			public const int textView1 = 2131230721;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int view_two = 2130903041;
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f070000
			public const int activity_main = 2131165184;
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050003
			public const int View1_Button_Text = 2131034115;
			
			// aapt resource value: 0x7f050006
			public const int View2_Button_Text = 2131034118;
			
			// aapt resource value: 0x7f050004
			public const int View_One_Title = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int View_Two_Title = 2131034117;
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			// aapt resource value: 0x7f050007
			public const int hello = 2131034119;
			
			// aapt resource value: 0x7f050001
			public const int hello_world = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int menu_settings = 2131034114;
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int AppBaseTheme = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int AppTheme = 2131099649;
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
